<?php

/**
 * PluginFilesToShareTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginFilesToShareTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginFilesToShareTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginFilesToShare');
    }
}