<?php

/**
 * PluginEmailsToSendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailsToSendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailsToSendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmailsToSend');
    }
    
    public static function getFilesByUserId($userId )
    {
      $query = Doctrine_Core::getTable('FilesToShare')->createQuery('u')
        ->where('u.user_id = ?', $userId)
      ;

      return $query->execute();
    }
}