<?php

/**
 * BaseFilesToShare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $file_name
 * @property string $email_sender
 * @property string $message
 * @property integer $times_downloads
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property Doctrine_Collection $EmailsToSend
 * 
 * @method string              getFileName()        Returns the current record's "file_name" value
 * @method string              getEmailSender()     Returns the current record's "email_sender" value
 * @method string              getMessage()         Returns the current record's "message" value
 * @method integer             getTimesDownloads()  Returns the current record's "times_downloads" value
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method sfGuardUser         getUser()            Returns the current record's "User" value
 * @method Doctrine_Collection getEmailsToSend()    Returns the current record's "EmailsToSend" collection
 * @method FilesToShare        setFileName()        Sets the current record's "file_name" value
 * @method FilesToShare        setEmailSender()     Sets the current record's "email_sender" value
 * @method FilesToShare        setMessage()         Sets the current record's "message" value
 * @method FilesToShare        setTimesDownloads()  Sets the current record's "times_downloads" value
 * @method FilesToShare        setUserId()          Sets the current record's "user_id" value
 * @method FilesToShare        setUser()            Sets the current record's "User" value
 * @method FilesToShare        setEmailsToSend()    Sets the current record's "EmailsToSend" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFilesToShare extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('files_to_share');
        $this->hasColumn('file_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_sender', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('times_downloads', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('EmailsToSend', array(
             'local' => 'id',
             'foreign' => 'file_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}