<?php

/**
 * EmailsToSendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailsToSendTable extends PluginEmailsToSendTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailsToSendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailsToSend');
    }
}